
// TODO: clean up imports

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.File;
import java.io.PrintWriter;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;
import javax.swing.text.JTextComponent;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author watet3953
 */
public class ReportCardProUI extends javax.swing.JFrame {

    /**
     * Creates new form ReportCardProUI
     */
    public ReportCardProUI() {
        initComponents();
        initComponentNames(jTabbedPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jFrameInput = new javax.swing.JPanel();
        jTFNameFirst = new javax.swing.JTextField();
        jTFNameLast = new javax.swing.JTextField();
        jTFSemester = new javax.swing.JTextField();
        jTFAverage = new javax.swing.JTextField();
        jTFID = new javax.swing.JTextField();
        jBttnAddClass = new javax.swing.JButton();
        jFrameClass0 = new javax.swing.JPanel();
        jTFClass0 = new javax.swing.JTextField();
        jTFMark0 = new javax.swing.JTextField();
        jTFCredit0 = new javax.swing.JTextField();
        jTFAverage0 = new javax.swing.JTextField();
        jTFAttendance0 = new javax.swing.JTextField();
        jTFComments0 = new javax.swing.JTextField();
        jBttnRemove0 = new javax.swing.JButton();
        jFrameProcess = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTFSNSV = new javax.swing.JTextField();
        jBttnRunSN = new javax.swing.JButton();
        jBttnAddScript = new javax.swing.JButton();
        jFramePrint = new javax.swing.JPanel();
        jBttnPrintSave = new javax.swing.JButton();
        jLblFormatType = new javax.swing.JLabel();
        jCBFormats = new javax.swing.JComboBox<>();
        jFramePreview = new javax.swing.JPanel();
        jBttnSaveFormat = new javax.swing.JButton();
        jFrameTop = new javax.swing.JPanel();
        jLblTitle = new javax.swing.JLabel();
        jBttnSave = new javax.swing.JButton();
        jBttnLoad = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jFrameInput.setLayout(new java.awt.GridLayout(10, 0));

        jTFNameFirst.setText("First Name");
        jTFNameFirst.setToolTipText("First Name");
        jFrameInput.add(jTFNameFirst);

        jTFNameLast.setText("Last Name");
        jTFNameLast.setToolTipText("Last Name");
        jFrameInput.add(jTFNameLast);

        jTFSemester.setText("Semester");
        jTFSemester.setToolTipText("Semester");
        jFrameInput.add(jTFSemester);

        jTFAverage.setEditable(false);
        jTFAverage.setText("Average");
        jTFAverage.setToolTipText("Average");
        jFrameInput.add(jTFAverage);

        jTFID.setText("Student ID");
        jTFID.setToolTipText("Student ID");
        jFrameInput.add(jTFID);

        jBttnAddClass.setText("Add Class");
        jBttnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddClassActionPerformed(evt);
            }
        });
        jFrameInput.add(jBttnAddClass);

        jFrameClass0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jFrameClass0.setLayout(new javax.swing.BoxLayout(jFrameClass0, javax.swing.BoxLayout.LINE_AXIS));

        jTFClass0.setText("Class 0");
        jTFClass0.setToolTipText("Class 0");
        jTFClass0.setMinimumSize(new java.awt.Dimension(40, 20));
        jFrameClass0.add(jTFClass0);

        jTFMark0.setText("Mark 0");
        jTFMark0.setToolTipText("Mark 0");
        jTFMark0.setMinimumSize(new java.awt.Dimension(40, 20));
        jFrameClass0.add(jTFMark0);

        jTFCredit0.setText("Credit 0");
        jTFCredit0.setToolTipText("Credit 0");
        jTFCredit0.setMinimumSize(new java.awt.Dimension(40, 20));
        jFrameClass0.add(jTFCredit0);

        jTFAverage0.setEditable(false);
        jTFAverage0.setText("Average 0");
        jTFAverage0.setToolTipText("Average 0");
        jTFAverage0.setMinimumSize(new java.awt.Dimension(40, 20));
        jFrameClass0.add(jTFAverage0);

        jTFAttendance0.setText("Attendance 0");
        jTFAttendance0.setToolTipText("Attendance 0");
        jTFAttendance0.setMinimumSize(new java.awt.Dimension(40, 20));
        jFrameClass0.add(jTFAttendance0);

        jTFComments0.setText("Comments 0");
        jTFComments0.setToolTipText("Comments 0");
        jTFComments0.setMinimumSize(new java.awt.Dimension(40, 20));
        jFrameClass0.add(jTFComments0);

        jBttnRemove0.setText("Remove Class");
        jBttnRemove0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnRemove0ActionPerformed(evt);
            }
        });
        jFrameClass0.add(jBttnRemove0);

        jFrameInput.add(jFrameClass0);

        jTabbedPane.addTab("Input", jFrameInput);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("[SN]"));

        jBttnRunSN.setText("\"Run Script\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFSNSV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jBttnRunSN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(565, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFSNSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jBttnRunSN)
                .addContainerGap())
        );

        jBttnAddScript.setText("\"Add Script\"");

        javax.swing.GroupLayout jFrameProcessLayout = new javax.swing.GroupLayout(jFrameProcess);
        jFrameProcess.setLayout(jFrameProcessLayout);
        jFrameProcessLayout.setHorizontalGroup(
            jFrameProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrameProcessLayout.createSequentialGroup()
                        .addComponent(jBttnAddScript, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrameProcessLayout.setVerticalGroup(
            jFrameProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBttnAddScript)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Process", jFrameProcess);

        jBttnPrintSave.setText("Print / Save");

        jLblFormatType.setText("Format Type :");

        jCBFormats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFramePreview.setBorder(javax.swing.BorderFactory.createTitledBorder("Window"));

        javax.swing.GroupLayout jFramePreviewLayout = new javax.swing.GroupLayout(jFramePreview);
        jFramePreview.setLayout(jFramePreviewLayout);
        jFramePreviewLayout.setHorizontalGroup(
            jFramePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        jFramePreviewLayout.setVerticalGroup(
            jFramePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jBttnSaveFormat.setText("\"Save Format\"");

        javax.swing.GroupLayout jFramePrintLayout = new javax.swing.GroupLayout(jFramePrint);
        jFramePrint.setLayout(jFramePrintLayout);
        jFramePrintLayout.setHorizontalGroup(
            jFramePrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFramePrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePrintLayout.createSequentialGroup()
                        .addComponent(jLblFormatType, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBFormats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBttnSaveFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBttnPrintSave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jFramePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFramePrintLayout.setVerticalGroup(
            jFramePrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePrintLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jBttnPrintSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFramePrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblFormatType)
                    .addComponent(jCBFormats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBttnSaveFormat)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(jFramePrintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFramePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Print", jFramePrint);

        jLblTitle.setText("Report Card Pro");

        jBttnSave.setLabel("Save");
        jBttnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSaveActionPerformed(evt);
            }
        });

        jBttnLoad.setText("Load");

        javax.swing.GroupLayout jFrameTopLayout = new javax.swing.GroupLayout(jFrameTop);
        jFrameTop.setLayout(jFrameTopLayout);
        jFrameTopLayout.setHorizontalGroup(
            jFrameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameTopLayout.createSequentialGroup()
                .addComponent(jLblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBttnLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBttnSave))
        );

        jFrameTopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBttnLoad, jBttnSave});

        jFrameTopLayout.setVerticalGroup(
            jFrameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrameTopLayout.createSequentialGroup()
                .addGroup(jFrameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFrameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBttnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBttnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );

        jBttnSave.getAccessibleContext().setAccessibleName("jBttnSave");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addComponent(jFrameTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jFrameTop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane))
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("jTabbedPane");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentNames(Component object) { // not sure if this could really be automated
        if (object instanceof JTextComponent) {
            object.setName(((JTextComponent)(object)).getText());
        }
        if (object instanceof Container) {
            try {
                Component[] objects = ((Container)(object)).getComponents();
                for (Component object1 : objects) {
                    initComponentNames(object1);
                }
            } catch (Exception e) {}
        }
    }
    
    public String dataPath = "";
    
    private String queryDataPath() {
        JOptionPane.showMessageDialog(null,"Please select the data folder.","Data Path Unspecified",1);
        JFileChooser fc = new JFileChooser("");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (fc.showOpenDialog(null) ==  JFileChooser.APPROVE_OPTION) {
            return fc.getSelectedFile().getAbsolutePath();
        }
        return "";
    }
    
    private String[][] returnContents(Component object) { // this whole function has some nasty typecasting, but it should work
        ArrayList<String> exportContent  = new ArrayList<>();
        ArrayList<String> exportName  = new ArrayList<>();
        
        if (object instanceof JTextComponent) {
            exportName.add(((JTextComponent)(object)).getName());
            exportContent.add(((JTextComponent)(object)).getText());
            //System.out.println(((JTextComponent)(object)).getName());
        }
        if (object instanceof Container) {
            Component[] objects = ((Container)(object)).getComponents();
            for (Component object1 : objects) {
                String[][] inFeed = returnContents(object1);
                for (int y = 0; y < inFeed[0].length; y++) {
                    exportName.add(inFeed[0][y]);
                    exportContent.add(inFeed[1][y]);
                }
            }
        }
    String[][] output = new String[2][exportContent.size()];
    if (exportContent.isEmpty()) {
        return output;
    }
    
    System.out.println(output.length);
    System.out.println(output[0].length);
    System.out.println(output[1].length);
    for (int x = 0; x < exportName.size(); x++) {
        output[0][x] = exportName.get(x);
        System.out.println(output[0][x]);
    }
    for (int x = 0; x < exportContent.size(); x++) {
        output[1][x] = exportContent.get(x);
        System.out.println(output[1][x]);
    }
    return output;  
    }
    
    private void jBttnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSaveActionPerformed
        // Get data path
        if (dataPath.isEmpty()) {
            dataPath = queryDataPath();
            if (dataPath.isEmpty()) {
                return;
            }
        }
        // check if file exists, prompt user if does
        String studentID = jTFID.getText();
        File studentFile = new File(dataPath, studentID + ".csv");
        if (studentFile.canRead()) {
           if (JOptionPane.showConfirmDialog(null,"Would you like to overwrite the existing file?","File Already Exists",1) == javax.swing.JOptionPane.NO_OPTION) {
               return;
           } 
        } else {
            try {
                studentFile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(ReportCardProUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String[][] variables = returnContents(jFrameInput);
        PrintWriter fileOut = null;
        try {
            fileOut = new PrintWriter(studentFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReportCardProUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        String line = "";
        
        for (String variable : variables[0]) {
            System.out.println(variable);
            line = line.concat(variable + ",");
        }
        
        fileOut.println(line);
        
        line = "";
        
        for (String variable : variables[1]) {
            System.out.println(variable);
            line = line.concat(variable + ",");
        }
        
        fileOut.println(line);
        fileOut.close();
        System.out.println(dataPath);
    }//GEN-LAST:event_jBttnSaveActionPerformed

    private int curIncrement = 0;
    
    private String incrementString(String in) {
        if (in == null || in.isEmpty()) {
            //return "1";
            return Integer.toString(curIncrement);
        }
        if (!in.endsWith("[0-9]")) {
            //return in + "1";
            return in + Integer.toString(curIncrement);
        }
        int readerPos = in.length();
        while (readerPos > 0) {
            readerPos--;
            if (!Character.isDigit(in.charAt(readerPos))) {
                readerPos++;
                break;
            }
        }
        int curValue = Integer.parseInt(in.substring(readerPos));
        String shavedString = in.substring(0,readerPos - 1);
        //return shavedString + Integer.toString(curValue++);
        return shavedString + Integer.toString(curIncrement);
    }
    
    
    
    private Object deepIncrementName(Object in) {
        if (in instanceof Container) {
            Component[] children = ((Container)(in)).getComponents();
            for (Component child1 : children) {
                Object returnedChild = deepIncrementName(child1);
                ((Container) in).remove(child1);
                ((Container) in).add((Component)(returnedChild));
            }
        }
        if (in instanceof Component) {  
            Component inC = (Component)(in);
            inC.setName(incrementString(inC.getName()));
            if (inC instanceof JTextField) {
                JTextField inTF = (JTextField)(inC);
                inTF.setToolTipText(inTF.getName());
                inTF.setText(inTF.getName());
                return inTF;
            }
            return inC;
        }
        return in;
    }
    
    private Object deepCopyUI(Object in) throws IOException, ClassNotFoundException {
        ByteArrayOutputStream bao = new ByteArrayOutputStream();
        ObjectOutputStream oos = new ObjectOutputStream(bao);
        oos.writeObject(in);
        
        ByteArrayInputStream bai = new ByteArrayInputStream(bao.toByteArray());
        ObjectInputStream ois = new ObjectInputStream(bai);
        Object copied = ois.readObject();
        return copied;
    }
    
    private void jBttnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddClassActionPerformed
        JPanel copy = null;
        try {
            copy = (JPanel)(deepCopyUI(jFrameClass0));
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(ReportCardProUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        curIncrement++;
        copy = (JPanel)(deepIncrementName(copy));
        jFrameInput.add(copy); // not sure if all 3 of these are needed, probably good to be safe
        jFrameInput.revalidate();
        jFrameInput.repaint();
        
        
    }//GEN-LAST:event_jBttnAddClassActionPerformed

    private void jBttnRemove0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnRemove0ActionPerformed
        // this might work as a custom button class (with the action performed action tied to deleting it's parent)
    }//GEN-LAST:event_jBttnRemove0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportCardProUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReportCardProUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAddClass;
    private javax.swing.JButton jBttnAddScript;
    private javax.swing.JButton jBttnLoad;
    private javax.swing.JButton jBttnPrintSave;
    private javax.swing.JButton jBttnRemove0;
    private javax.swing.JButton jBttnRunSN;
    private javax.swing.JButton jBttnSave;
    private javax.swing.JButton jBttnSaveFormat;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBFormats;
    private javax.swing.JPanel jFrameClass0;
    private javax.swing.JPanel jFrameInput;
    private javax.swing.JPanel jFramePreview;
    private javax.swing.JPanel jFramePrint;
    private javax.swing.JPanel jFrameProcess;
    private javax.swing.JPanel jFrameTop;
    private javax.swing.JLabel jLblFormatType;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFAttendance0;
    private javax.swing.JTextField jTFAverage;
    private javax.swing.JTextField jTFAverage0;
    private javax.swing.JTextField jTFClass0;
    private javax.swing.JTextField jTFComments0;
    private javax.swing.JTextField jTFCredit0;
    private javax.swing.JTextField jTFID;
    private javax.swing.JTextField jTFMark0;
    private javax.swing.JTextField jTFNameFirst;
    private javax.swing.JTextField jTFNameLast;
    private javax.swing.JTextField jTFSNSV;
    private javax.swing.JTextField jTFSemester;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
